############################
## CHANGE THESE
############################

baseURL: 'https://szabolcs.pages.dev'
title: 'Szabolcs Nógrádi'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


